# --- !Ups

CREATE TABLE TB_USUARIO (
  ID 		INTEGER NOT NULL AUTO_INCREMENT, 
  EMAIL 	VARCHAR(50), 
  SENHA 	VARCHAR(12),
  
  PRIMARY KEY (ID)
); 


CREATE TABLE TB_FILME (
  ID 			INTEGER NOT NULL AUTO_INCREMENT, 
  TITULO 		VARCHAR(50), 
  DIRETOR 		VARCHAR(50),
  ANO_PRODUCAO 	INTEGER(4),
  
  PRIMARY KEY (ID)
); 

CREATE TABLE TB_FILME_USUARIO (
	 ID_USUARIO	INTEGER UNSIGNED REFERENCES TB_USUARIO(ID),
	 ID_FILME	INTEGER UNSIGNED REFERENCES TB_FILME(ID),
	 NOTA 		INTEGER(1)
);

ALTER TABLE TB_FILME_USUARIO
ADD PRIMARY KEY (ID_USUARIO, ID_FILME);

# --- !Downs

DROP TABLE User;